-- RippleStudio Online · initial schema
-- Run once in a new EU Supabase project. The destructive-operation warning is
-- about replacing access rules and grants below; this file does not drop data.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Razz',
  avatar text,                       -- a small square picture, stored inline as a data URL
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity (start with 1000000) primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  notes text,
  avatar text,                       -- a small square picture, stored inline as a data URL
  created_at timestamptz not null default now(),
  unique (id, user_id)
);

create table if not exists public.projects (
  id bigint generated by default as identity (start with 1000000) primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id bigint,
  project_id text,
  title text not null,
  status text not null default 'lead' check (status in ('lead','footage sent','editing','review','revisions','final delivery','payment','closed')),
  services jsonb not null default '[]'::jsonb,
  footage_downloaded boolean not null default false,
  vsl_package jsonb,
  operator text not null default 'Razz',
  footage_received_at date,
  first_cut_sent_at date,
  delivered_at date,
  paid_at date,
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid','pending','paid')),
  notes text,
  negotiated_price numeric(12,2),
  track_time boolean not null default false,
  created_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (client_id, user_id) references public.clients(id, user_id) on delete cascade
);

create table if not exists public.payments (
  id bigint generated by default as identity (start with 1000000) primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id bigint,
  amount numeric(12,2) not null,
  currency text not null default 'EUR',
  usd_equivalent numeric(12,2),
  service_description text,
  date date not null default current_date,
  notes text,
  invoice_number text,
  created_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (client_id, user_id) references public.clients(id, user_id) on delete cascade
);

create table if not exists public.payment_projects (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  payment_id bigint not null,
  project_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (payment_id, project_id),
  foreign key (payment_id, user_id) references public.payments(id, user_id) on delete cascade,
  foreign key (project_id, user_id) references public.projects(id, user_id) on delete cascade
);

create table if not exists public.time_entries (
  id bigint generated by default as identity (start with 1000000) primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  project_id bigint not null,
  vsl_item text,
  stage text check (stage is null or stage in ('project_setup','sync','rough_cut','fine_cut','animation','color','audio','captions','export_upload','revisions')),
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_seconds integer,
  paused_at timestamptz,
  paused_seconds integer not null default 0,
  adjustment_seconds integer not null default 0,
  note text,
  created_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (project_id, user_id) references public.projects(id, user_id) on delete cascade
);

create unique index if not exists one_active_timer_per_user on public.time_entries (user_id) where ended_at is null;
create index if not exists projects_user_status_idx on public.projects (user_id, status);
create index if not exists payments_user_date_idx on public.payments (user_id, date desc);
create index if not exists time_entries_user_project_idx on public.time_entries (user_id, project_id, started_at desc);

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.projects enable row level security;
alter table public.payments enable row level security;
alter table public.payment_projects enable row level security;
alter table public.time_entries enable row level security;

revoke all on public.profiles, public.clients, public.projects, public.payments, public.payment_projects, public.time_entries from anon;
grant select, insert, update, delete on public.profiles, public.clients, public.projects, public.payments, public.payment_projects, public.time_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "owner profile" on public.profiles;
create policy "owner profile" on public.profiles for all to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "owner clients" on public.clients;
create policy "owner clients" on public.clients for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "owner projects" on public.projects;
create policy "owner projects" on public.projects for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "owner payments" on public.payments;
create policy "owner payments" on public.payments for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "owner payment projects" on public.payment_projects;
create policy "owner payment projects" on public.payment_projects for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "owner time entries" on public.time_entries;
create policy "owner time entries" on public.time_entries for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.seed_profile() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', 'Razz')) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup after insert on auth.users for each row execute function public.seed_profile();

-- Logins created before this file ran get their profile here.
insert into public.profiles (id) select id from auth.users on conflict (id) do nothing;

create or replace function public.ping() returns boolean language sql stable as $$ select true $$;
revoke all on function public.ping() from public;
grant execute on function public.ping() to anon, authenticated;
